export const PUSH_SAMPLE_BUTTON_REQUEST = "PUSH_SAMPLE_BUTTON_REQUEST";
export const PUSH_SAMPLE_HEADER_REQUEST = "PUSH_SAMPLE_HEADER_REQUEST";
export const PUSH_SAMPLE_TAB_REQUEST = "PUSH_SAMPLE_TAB_REQUEST";